import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.LAKEMATCH_PLAYWRIGHT_MODULE || '/Users/laurent.fabre/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root = path.resolve(process.argv[2] || 'data/app-acceptance-v1');
const url = process.argv[3] || 'http://127.0.0.1:9034';
const browser = await chromium.launch({headless:true, executablePath:process.env.LAKEMATCH_CHROMIUM_EXECUTABLE});
const page = await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto(url, {timeout:30000});
  await page.getByRole('heading',{name:'Do these records describe the same entity?'}).waitFor();
  if (await page.getByText('Genie',{exact:true}).count()) throw new Error('Genie visible while disabled');
  await page.screenshot({path:path.join(root,'review-desktop.png'),fullPage:true});
  const get = async endpoint => {const r=await page.request.get(url+'/api/'+endpoint);if(!r.ok())throw new Error(`${endpoint}: ${r.status()}`);return await r.json();};
  let queue=await get('queue?limit=100');
  if(queue.length!==24)throw new Error('Expected a fresh 24-pair fixture');
  const expected=[...queue].sort((a,b)=>Math.abs(a.probability-a.threshold)-Math.abs(b.probability-b.threshold)||(b.impact-a.impact)||a.pair_id.localeCompare(b.pair_id));
  if(JSON.stringify(queue)!==JSON.stringify(expected)) throw new Error('Queue order differs');
  await page.keyboard.press('m');
  await page.getByRole('alert').filter({hasText:'Add a reason'}).waitFor();
  const first=queue[0];
  const isMatch=first.a_id.slice(1)===first.b_id.slice(1);
  await page.getByLabel('What informed your decision?').fill('Synthetic fixture: names and group inspected through keyboard review.');
  await page.keyboard.press('Escape');
  await page.keyboard.press(isMatch?'m':'n');
  await page.getByRole('status').filter({hasText:'Saved'}).waitFor();
  const afterKeyboard=await get('reviews');
  if(afterKeyboard.length!==1 || afterKeyboard[0].pair_id!==first.pair_id)throw new Error('Keyboard review did not persist');
  const receipts=[afterKeyboard[0]];
  queue=await get('queue?limit=100');
  for(let i=0;i<19;i++){
    const p=queue[i];const decision=i===18?'unsure':p.a_id.slice(1)===p.b_id.slice(1)?'match':'no_match';
    const body={request_id:crypto.randomUUID(),pair_id:p.pair_id,model_version:p.model_version,decision,reason:decision==='unsure'?'Acceptance fixture: intentionally unresolved.':'Synthetic fixture: compared name and group.'};
    const r=await page.request.post(url+'/api/reviews',{data:body});
    if(!r.ok())throw new Error(`Review HTTP ${r.status()}: ${await r.text()}`);
    const saved=await r.json();receipts.push(saved);
    const retry=await page.request.post(url+'/api/reviews',{data:body});
    if(JSON.stringify(await retry.json())!==JSON.stringify(saved))throw new Error('Retry changed the review');
  }
  const snapshot=await get('training-labels');
  if(snapshot.reviews.length!==20||snapshot.labels.length!==19||snapshot.excluded_unsure!==1)throw new Error('Bad training snapshot');
  if(!receipts.every(r=>r.user&&r.reviewed_at&&r.model_version&&r.reason))throw new Error('Incomplete provenance');
  fs.writeFileSync(path.join(root,'http-snapshot.json'),JSON.stringify(snapshot,null,2)+'\n');
  await page.reload();
  await page.getByRole('button',{name:'Statistics',exact:true}).click();
  await page.getByRole('heading',{name:'Model quality over time'}).waitFor();
  await page.getByRole('cell',{name:'synthetic record-disjoint validation'}).waitFor();
  await page.screenshot({path:path.join(root,'statistics-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Review history',exact:true}).click();
  await page.getByRole('heading',{name:'Saved reviews'}).waitFor();
  await page.locator('.history-list > li').first().waitFor();
  if(await page.locator('.history-list > li').count()!==20)throw new Error('History lost saved reviews');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:/Review queue/}).click();
  await page.getByRole('heading',{name:'Do these records describe the same entity?'}).waitFor();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(overflow)throw new Error('Mobile page overflows viewport');
  await page.screenshot({path:path.join(root,'review-mobile.png'),fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  fs.writeFileSync(path.join(root,'browser-report.json'),JSON.stringify({status:'passed',url,reviewed:20,keyboard_review:true,retry_idempotent:true,provenance:true,genie_hidden:true,mobile_no_overflow:true,page_errors:errors},null,2)+'\n');
  console.log('20 HTTP reviews, keyboard workflow, statistics, history and mobile checks passed');
} finally {await browser.close();}
