/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as SidebarLabelsRouteImport } from './../routes/_sidebar/labels'
import { Route as SidebarReviewRouteImport } from './../routes/_sidebar/review'
import { Route as SidebarStatsRouteImport } from './../routes/_sidebar/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLabelsRoute = SidebarLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarReviewRoute = SidebarReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarStatsRoute = SidebarStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labels': typeof SidebarLabelsRoute
  '/review': typeof SidebarReviewRoute
  '/stats': typeof SidebarStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labels': typeof SidebarLabelsRoute
  '/review': typeof SidebarReviewRoute
  '/stats': typeof SidebarStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/labels': typeof SidebarLabelsRoute
  '/_sidebar/review': typeof SidebarReviewRoute
  '/_sidebar/stats': typeof SidebarStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/labels' | '/review' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/labels' | '/review' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/labels'
    | '/_sidebar/review'
    | '/_sidebar/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/labels': {
      id: '/_sidebar/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof SidebarLabelsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/review': {
      id: '/_sidebar/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof SidebarReviewRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/stats': {
      id: '/_sidebar/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof SidebarStatsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarLabelsRoute: typeof SidebarLabelsRoute
  SidebarReviewRoute: typeof SidebarReviewRoute
  SidebarStatsRoute: typeof SidebarStatsRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarLabelsRoute: SidebarLabelsRoute,
  SidebarReviewRoute: SidebarReviewRoute,
  SidebarStatsRoute: SidebarStatsRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
